"""Writes sw.js, the service worker that makes the hosted app work offline after the first visit.
Run after changing any app file:  python tools/build-sw.py   (the cache name is a hash of the files, so phones refresh)."""
import hashlib, os
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
files = ["./", "index.html", "manifest.webmanifest"]
for d in ("css", "js", "data", "fonts", "vendor", "icons"):
    for base, _, names in os.walk(os.path.join(ROOT, d)):
        for n in sorted(names):
            files.append(os.path.relpath(os.path.join(base, n), ROOT).replace(os.sep, "/"))
h = hashlib.sha1()
for f in files:
    p = os.path.join(ROOT, f)
    if os.path.isfile(p): h.update(f.encode()); h.update(open(p, "rb").read())
version = h.hexdigest()[:10]
js = """/* GENERATED by tools/build-sw.py. Cache-first so the app opens offline; a new build gets a new cache name. */
const CACHE = 'offer-ready-%s';
const FILES = %s;
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => Promise.all(FILES.map(f => c.add(f).catch(() => {})))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k.startsWith('offer-ready-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET' || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(hit => hit || fetch(e.request).then(r => {
    if (r.ok) { const copy = r.clone(); caches.open(CACHE).then(c => c.put(e.request, copy)); }
    return r;
  }).catch(() => e.request.mode === 'navigate' ? caches.match('index.html') : Response.error())));
});
""" % (version, __import__("json").dumps(files))
open(os.path.join(ROOT, "sw.js"), "w", encoding="utf-8").write(js)
print("sw.js:", len(files), "files, cache offer-ready-" + version)
