"""Build data/resources.js from source/README.md plus tools/resource-tags.json.

Every [title](http...) link under the README's curated sections (from '## Roadmaps' to
the '## 🤝 Contributing' heading) becomes one entry. Links outside that range (badges,
repo and sponsor links) are the README's own chrome and are listed in CHROME below.
Run: python tools/build-resources.py. Fails if a link has no tags or a tag has no link.
"""
import json, re, sys, io
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TYPES = 'video book course sheet tool community article repo other'.split()
COSTS = 'free paid unknown'.split()
LEVELS = 'beginner intermediate advanced all'.split()
LINK = re.compile(r'\[([^\]]+)\]\((https?://[^)\s]+)\)')

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
lines = (ROOT / 'source/README.md').read_text(encoding='utf-8').split('\n')
tags = json.loads((ROOT / 'tools/resource-tags.json').read_text(encoding='utf-8'))
tags = {k: v for k, v in tags.items() if not k.startswith('_')}

# Parse: ## heading = category, ### heading = group.
start = next(i for i, l in enumerate(lines) if l.startswith('## Roadmaps'))
end = next(i for i, l in enumerate(lines) if l.startswith('## ') and 'Contributing' in l)
cat = group = ''
links = []  # (title, url, category, group)
for l in lines[start:end]:
    if l.startswith('## '):
        cat, group = l[3:].strip(), ''
    elif l.startswith('### '):
        group = l[4:].strip()
    for title, url in LINK.findall(l):
        links.append((title.strip(), url, cat, group))

# Everything else in the README must be known chrome, so no link is silently skipped.
CHROME_OK = lambda u: any(s in u for s in ('img.shields.io', 'github.com/avinash201199/DSA-KIT', 'makeapullrequest.com', 'opensource.org/licenses', 'x.com/AvinashSingh_20'))
all_urls = set(re.findall(r'https?://[^\s)\]>]+', '\n'.join(lines)))
urls = {u for _, u, _, _ in links}
chrome = all_urls - urls
bad = [u for u in chrome if not CHROME_OK(u)]
if bad:
    sys.exit('FAIL: links outside the curated sections that are not known chrome:\n  ' + '\n  '.join(sorted(bad)))

# Tag checks. Keys are 'url' or 'url|Title' (a per-title override, only 'flag' here).
base = {k: v for k, v in tags.items() if '|' not in k}
over = {k: v for k, v in tags.items() if '|' in k}
missing = sorted(urls - set(base))
stale = sorted(set(base) - urls)
titles = {u + '|' + t for t, u, _, _ in links}
stale += sorted(set(over) - titles)
errs = []
if missing: errs.append('README links with no tags:\n  ' + '\n  '.join(missing))
if stale: errs.append('tags that match no README link:\n  ' + '\n  '.join(stale))
for u, v in base.items():
    if not (isinstance(v, list) and len(v) == 6): errs.append('bad tag shape: ' + u); continue
    if v[0] not in TYPES or v[1] not in COSTS or v[2] not in LEVELS: errs.append('bad type/cost/level: ' + u)
    if not v[3].strip(): errs.append('empty note: ' + u)
if errs: sys.exit('FAIL\n' + '\n'.join(errs))

out = []
for i, (title, url, c, g) in enumerate(links, 1):
    t = base[url]
    flag = over.get(url + '|' + title, {}).get('flag', t[5])
    e = {'id': 'r%03d' % i, 'title': title, 'url': url, 'category': c, 'group': g, 'type': t[0], 'cost': t[1],
         'level': t[2], 'note': t[3], 'start': bool(t[4])}
    if flag: e['flag'] = flag
    out.append(e)

body = ('/* GENERATED by tools/build-resources.py from source/README.md and tools/resource-tags.json.\n'
        '   Do not edit by hand: edit the generator or its tag map, then run it again. */\n'
        'window.OR = window.OR || {};\nOR.resources = ' + json.dumps(out, ensure_ascii=False, indent=1) + ';\n')
(ROOT / 'data/resources.js').write_text(body, encoding='utf-8')

cats = {}
for e in out: cats[e['category']] = cats.get(e['category'], 0) + 1
print('README distinct http(s) links: %d (curated %d + chrome %d)' % (len(all_urls), len(urls), len(chrome)))
print('link occurrences (entries): %d, distinct URLs: %d' % (len(out), len(urls)))
print('categories: %d' % len(cats)); [print('  %-40s %d' % kv) for kv in cats.items()]
print('start picks: %d, flagged: %d' % (sum(e['start'] for e in out), sum('flag' in e for e in out)))
assert len(urls) + len(chrome) == len(all_urls)
